development:
  adapter: postgresql
  database: weather-app_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: weather-app-test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: weather-app_production
  pool: 5
  timeout: 5000
